# Generated by Django 2.1.7 on 2019-04-28 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('end_datetime', models.DateTimeField(verbose_name='结束时间')),
                ('container_id', models.CharField(max_length=128, verbose_name='容器ID')),
                ('container_url', models.CharField(max_length=128, verbose_name='容器映射出来的链接')),
            ],
            options={
                'abstract': False,
                'verbose_name': '记录日期',
            },
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('end_datetime', models.DateTimeField(verbose_name='结束时间')),
                ('repositiry', models.CharField(max_length=128, verbose_name='镜像名称')),
                ('tag', models.CharField(max_length=128, verbose_name='镜像标签')),
                ('size', models.CharField(max_length=128, verbose_name='镜像大小')),
            ],
            options={
                'abstract': False,
                'verbose_name': '记录日期',
            },
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='image_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DockerImage'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
